export type AreaService = 'repair' | 'clean' | 'both'

export interface AreaData {
  slug: string          // URL slug: 금천-에어컨수리
  name: string          // 금천구
  shortName: string     // 금천
  service: AreaService
  dongs: string[]       // 동 목록
  description: string   // meta description
  h1: string
  subTitle: string
  lat: number
  lng: number
}

export const AREAS: AreaData[] = [
  {
    slug: '금천-에어컨수리',
    name: '금천구',
    shortName: '금천',
    service: 'repair',
    dongs: ['가산동', '독산동', '시흥동'],
    h1: '금천구 에어컨 수리',
    subTitle: '가산 · 독산 · 시흥 당일 출장',
    description: '금천구 에어컨 수리 전문 에어컨해결사. 가스충전·누수·냉방불량 당일 출장. 가산·독산·시흥 전 지역 방문 수리, 합리적인 가격.',
    lat: 37.4564,
    lng: 126.8954,
  },
  {
    slug: '관악-에어컨수리',
    name: '관악구',
    shortName: '관악',
    service: 'repair',
    dongs: ['신림동', '봉천동', '남현동'],
    h1: '관악구 에어컨 수리',
    subTitle: '신림 · 봉천 · 남현 당일 출장',
    description: '관악구 에어컨 수리 전문 에어컨해결사. 가스충전·누수·냉방불량 당일 출장. 신림·봉천·남현 전 지역 방문 수리, 합리적인 가격.',
    lat: 37.4784,
    lng: 126.9516,
  },
  {
    slug: '구로-에어컨수리',
    name: '구로구',
    shortName: '구로',
    service: 'repair',
    dongs: ['구로동', '개봉동', '오류동', '항동'],
    h1: '구로구 에어컨 수리',
    subTitle: '구로 · 개봉 · 오류 당일 출장',
    description: '구로구 에어컨 수리 전문 에어컨해결사. 가스충전·누수·냉방불량 당일 출장. 구로·개봉·오류·항동 전 지역 방문 수리.',
    lat: 37.4954,
    lng: 126.8874,
  },
  {
    slug: '영등포-에어컨수리',
    name: '영등포구',
    shortName: '영등포',
    service: 'repair',
    dongs: ['영등포동', '여의도동', '당산동', '양평동'],
    h1: '영등포구 에어컨 수리',
    subTitle: '여의도 · 당산 · 양평 당일 출장',
    description: '영등포구 에어컨 수리 전문 에어컨해결사. 가스충전·누수·냉방불량 당일 출장. 여의도·당산·양평·영등포 전 지역 방문 수리.',
    lat: 37.5264,
    lng: 126.8963,
  },
  {
    slug: '광명-에어컨수리',
    name: '광명시',
    shortName: '광명',
    service: 'repair',
    dongs: ['광명동', '철산동', '하안동', '소하동'],
    h1: '광명시 에어컨 수리',
    subTitle: '광명 · 철산 · 하안 · 소하 당일 출장',
    description: '광명시 에어컨 수리 전문 에어컨해결사. 가스충전·누수·냉방불량 당일 출장. 광명·철산·하안·소하 전 지역 방문 수리.',
    lat: 37.4786,
    lng: 126.8664,
  },
  {
    slug: '안양-에어컨수리',
    name: '안양시',
    shortName: '안양',
    service: 'repair',
    dongs: ['안양동', '비산동', '관양동', '평촌동', '호계동'],
    h1: '안양시 에어컨 수리',
    subTitle: '안양 · 비산 · 평촌 · 호계 당일 출장',
    description: '안양시 에어컨 수리 전문 에어컨해결사. 가스충전·누수·냉방불량 당일 출장. 안양·비산·관양·평촌·호계 전 지역 방문 수리.',
    lat: 37.3943,
    lng: 126.9568,
  },
  {
    slug: '동작-에어컨청소',
    name: '동작구',
    shortName: '동작',
    service: 'clean',
    dongs: ['사당동', '노량진동', '상도동', '흑석동'],
    h1: '동작구 에어컨 청소',
    subTitle: '사당 · 노량진 · 상도 · 흑석 당일 출장',
    description: '동작구 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 사당·노량진·상도·흑석 전 지역 방문 청소.',
    lat: 37.5124,
    lng: 126.9394,
  },
  {
    slug: '강동-에어컨청소',
    name: '강동구',
    shortName: '강동',
    service: 'clean',
    dongs: ['천호동', '암사동', '길동', '명일동'],
    h1: '강동구 에어컨 청소',
    subTitle: '천호 · 암사 · 길동 · 명일 당일 출장',
    description: '강동구 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 천호·암사·길동·명일 전 지역 방문 청소.',
    lat: 37.5301,
    lng: 127.1238,
  },
  {
    slug: '노원-에어컨청소',
    name: '노원구',
    shortName: '노원',
    service: 'clean',
    dongs: ['상계동', '중계동', '월계동', '공릉동'],
    h1: '노원구 에어컨 청소',
    subTitle: '상계 · 중계 · 월계 · 공릉 당일 출장',
    description: '노원구 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 상계·중계·월계·공릉 전 지역 방문 청소.',
    lat: 37.6543,
    lng: 127.0568,
  },
  {
    slug: '중랑-에어컨청소',
    name: '중랑구',
    shortName: '중랑',
    service: 'clean',
    dongs: ['묵동', '신내동', '망우동', '면목동'],
    h1: '중랑구 에어컨 청소',
    subTitle: '묵동 · 신내 · 망우 · 면목 당일 출장',
    description: '중랑구 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 묵동·신내·망우·면목 전 지역 방문 청소.',
    lat: 37.6063,
    lng: 127.0925,
  },
  {
    slug: '동대문-에어컨청소',
    name: '동대문구',
    shortName: '동대문',
    service: 'clean',
    dongs: ['전농동', '답십리동', '장안동', '회기동'],
    h1: '동대문구 에어컨 청소',
    subTitle: '전농 · 답십리 · 장안 · 회기 당일 출장',
    description: '동대문구 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 전농·답십리·장안·회기 전 지역 방문 청소.',
    lat: 37.5744,
    lng: 127.0397,
  },
  {
    slug: '성북-에어컨청소',
    name: '성북구',
    shortName: '성북',
    service: 'clean',
    dongs: ['성북동', '정릉동', '길음동', '돈암동'],
    h1: '성북구 에어컨 청소',
    subTitle: '성북 · 정릉 · 길음 · 돈암 당일 출장',
    description: '성북구 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 성북·정릉·길음·돈암 전 지역 방문 청소.',
    lat: 37.5894,
    lng: 127.0167,
  },
  {
    slug: '강북-에어컨청소',
    name: '강북구',
    shortName: '강북',
    service: 'clean',
    dongs: ['미아동', '번동', '수유동', '우이동'],
    h1: '강북구 에어컨 청소',
    subTitle: '미아 · 번동 · 수유 · 우이 당일 출장',
    description: '강북구 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 미아·번동·수유·우이 전 지역 방문 청소.',
    lat: 37.6396,
    lng: 127.0257,
  },
  {
    slug: '하남-에어컨청소',
    name: '하남시',
    shortName: '하남',
    service: 'clean',
    dongs: ['덕풍동', '신장동', '미사동', '감이동'],
    h1: '하남시 에어컨 청소',
    subTitle: '덕풍 · 신장 · 미사 · 감이 당일 출장',
    description: '하남시 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 덕풍·신장·미사·감이 전 지역 방문 청소.',
    lat: 37.5397,
    lng: 127.2148,
  },
  {
    slug: '남양주-에어컨청소',
    name: '남양주시',
    shortName: '남양주',
    service: 'clean',
    dongs: ['화도읍', '별내동', '다산동', '퇴계원읍'],
    h1: '남양주시 에어컨 청소',
    subTitle: '화도 · 별내 · 다산 · 퇴계원 당일 출장',
    description: '남양주시 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 화도·별내·다산·퇴계원 전 지역 방문 청소.',
    lat: 37.6360,
    lng: 127.2165,
  },
  {
    slug: '구리-에어컨청소',
    name: '구리시',
    shortName: '구리',
    service: 'clean',
    dongs: ['인창동', '교문동', '수택동', '토평동'],
    h1: '구리시 에어컨 청소',
    subTitle: '인창 · 교문 · 수택 · 토평 당일 출장',
    description: '구리시 에어컨 청소 전문 에어컨해결사. 분해세척·시스템에어컨·천장형 당일 출장. 인창·교문·수택·토평 전 지역 방문 청소.',
    lat: 37.5943,
    lng: 127.1296,
  },
]

export function getAreaBySlug(slug: string): AreaData | undefined {
  return AREAS.find(a => a.slug === slug)
}
